version: "3.7"

services:
  saoco-pgadmin:
    image: dpage/pgadmin4:6.3
    container_name: pgadmin.saoco
    environment:
      PGADMIN_DEFAULT_EMAIL: eduardo@saocoyson.net
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 8080:80
    logging:
      driver: none

  saoco-postgres:
    image: postgres:13-alpine
    container_name: postgres.saoco
    environment:
      POSTGRES_DB: saoco_mtf_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: saoco-mtf-network
