# Generated by Django 4.2.3 on 2023-07-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mtf", "0002_category_judge_sponsor_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                through="mtf.EventCategory",
                to="mtf.category",
                verbose_name="Categorías",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="instagram",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="judges",
            field=models.ManyToManyField(
                blank=True,
                db_table="mtf_event_judge",
                to="mtf.judge",
                verbose_name="Jueces",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logo",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True,
                db_table="mtf_event_sponsor",
                to="mtf.sponsor",
                verbose_name="Patrocinantes",
            ),
        ),
    ]
