# Generated by Django 4.2.3 on 2023-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mtf", "0003_alter_event_categories_alter_event_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Logo"
            ),
        ),
    ]
