# Generated by Django 4.2.3 on 2023-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtf', '0004_alter_event_instagram_alter_event_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Nombre correspondiente a la edición de este evento. Ejemplo: MTF 2023.', unique=True, verbose_name='Nombre'),
        ),
    ]
