# Generated by Django 4.1.7 on 2023-02-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Nombre de la academia"
                    ),
                ),
                (
                    "manager_id_document",
                    models.IntegerField(
                        unique=True, verbose_name="Cédula del director"
                    ),
                ),
                (
                    "manager_full_name",
                    models.CharField(
                        max_length=128,
                        verbose_name="Nombre completo del director",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Fecha de inscripción"),
                ),
            ],
            options={
                "verbose_name": "Academia",
                "verbose_name_plural": "Academias",
            },
        ),
        migrations.CreateModel(
            name="Dancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_document",
                    models.IntegerField(unique=True, verbose_name="Cédula"),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=128, verbose_name="Nombre completo"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "shirt_size",
                    models.CharField(
                        choices=[
                            ("xs", "Xs"),
                            ("s", "S"),
                            ("m", "M"),
                            ("l", "L"),
                            ("xl", "Xl"),
                        ],
                        default="m",
                        max_length=2,
                        verbose_name="Talla de franela",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        verbose_name="Género",
                    ),
                ),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="academies.academy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bailarín",
                "verbose_name_plural": "Bailarines",
            },
        ),
    ]
